# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# Setup
title:               Enze's Blog
tagline:             'Computer Science Student'
description:
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Enze Zhang
  url:               https://twitter.com/mdo
  email:             bestenze@gmail.com

# Custom vars
version:             1.0.0
